[workspace]
resolver = "2"
members = ["tsp_rust", "test-client", "petstore"]

[workspace.lints.clippy]
disallowed_names = "allow"

[profile.release]
lto = true
opt-level = "s"
codegen-units = 1
strip = true
